CREATE TABLE IF NOT EXISTS POSTS (
	  P_NUM LONG
	, T_NUM LONG
    , T_ORDER LONG
	, POSTER VARCHAR(40)
    , TIMESTAMP VARCHAR(40)
    , QUOTED1 VARCHAR(255)
    , QNUM1 LONG
    , QUOTED2 VARCHAR(255)
    , QNUM2 LONG
    , QUOTED3 VARCHAR(255)
    , QNUM3 LONG
    , MULTIQUOTE VARCHAR(1)
);