use aopol;
DROP TABLE IF EXISTS THREADS;
CREATE TABLE IF NOT EXISTS THREADS (
	  T_NUM INT
	, TITLE VARCHAR(255)
	, OP VARCHAR(40)
	, TIMESTAMP VARCHAR(40)
	, FIRST_READ DATETIME
	, LAST_REFRESH DATETIME
);

DROP TABLE IF EXISTS POSTS;
CREATE TABLE IF NOT EXISTS POSTS (
	  P_NUM INT
	, T_NUM INT
    , T_ORDER INT
	, POSTER VARCHAR(40)
    , TIMESTAMP VARCHAR(40)
    , QUOTED1 VARCHAR(40)
    , QNUM1 INT
    , QUOTED2 VARCHAR(40)
    , QNUM2 INT
    , QUOTED3 VARCHAR(40)
    , QNUM3 INT
    , MULTIQUOTE VARCHAR(1)
);

